local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Vock hub V1", "Serpent")

-- Game Scripts
local Tab = Window:NewTab("Game Scripts")
local Section = Tab:NewSection("Game Scripts")
Section:NewButton("Funky Friday Script", "beep beep bobobobo beep beep", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/wally-rblx/funky-friday-autoplay/main/main.lua",true))()
end)
Section:NewButton("RTX", "rtx", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/Qunce5TP",true))()
end)
Section:NewButton("doors script 1", "doorsscript1", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/slowpii/slowpihub/main/slowpihax",true))()
end)
Section:NewButton("doors script 2", "doorssscript2", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/GamingScripter/Darkrai-X/main/Games/Doors",true))()
end)
Section:NewButton("Build a boat for treasure", "buildaboat", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/1201for/V.G-Hub/main/V.Ghub",true))()
end)

--Character
local Tab = Window:NewTab("Character")
local Section = Tab:NewSection("Character")
Section:NewSlider("WalkSpeed", "Changes WalkSpeed", 500, 16, function(v) -- 500 (MaxValue) | 0 (MinValue)
    game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = v
end)
Section:NewSlider("JumpPower", "Changes JumpPower", 500, 50, function(v) -- 500 (MaxValue) | 0 (MinValue)
    game.Players.LocalPlayer.Character.Humanoid.JumpPower = v
    game.Players.LocalPlayer.Character.Humanoid.JumpHeight = v
end)
Section:NewButton("AnitCheat Bypass", "Works in most games but not all", function()
    Events = true -- Allow RemoteEvents (if true, blocks if false)
    Requests = false -- Allow RemoteFunctions (if true, blocks if false)
    Hitbox = true -- Allow Normal Hitbox (if true, attempt to bypass hbe if false)
    loadstring(game:HttpGet("https://pastebin.com/raw/MZrwt5Rm", true))()
    end)
Section:NewButton("noclip", "noclip", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/9LBsfRkD",true))()
end)
Section:NewButton("fly", "fly", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/kUXXL8Qf",true))()
end)

-- Settings
local Tab = Window:NewTab("Settings")
local Section = Tab:NewSection("Settings")
Section:NewKeybind("Toggle UI", "Toggle's UI", Enum.KeyCode.RightShift, function()
	Library:ToggleUI()
end)
Section:NewButton("antilag", "antilag", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/zaTGe6XX",true))()
    end)

--Credits
local Tab = Window:NewTab("Credits")
local Section = Tab:NewSection("Credits")
Section:NewButton("Made By Mistervock#3840", "author 1", function()
    end)
--Keys
local Tab = Window:NewTab("Keys")
local Section = Tab:NewSection("Keys")
Section:NewButton("key doors script 1 link: https://shrlink.top/chylV", "doorskey", function()
end)
